name: "Lint"

on:
  workflow_call:
    inputs:
      node-version:
        type: string
        default: "24"
      install:
        type: string
        default: "npm ci"
      lint:
        type: string
        default: "npm run lint"
      prettier:
        type: string
        default: "npm run prettier:check"
      yamllint:
        type: boolean
        default: true
      actionlint:
        type: boolean
        default: true
      action:
        type: string
        default: "action.yml"

#concurrency:
#  group: ${{ github.workflow }}-${{ github.ref }}
#  cancel-in-progress: true

jobs:
  lint:
    name: "Lint"
    if: ${{ !contains(github.event.head_commit.message, '#nolint') }}
    runs-on: ubuntu-latest
    timeout-minutes: 5

    permissions:
      pull-requests: write

    steps:
      - name: "Checkout"
        uses: actions/checkout@v5

      - name: "Setup Node"
        if: ${{ inputs.node-version != '' }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ inputs.node-version }}

      - name: "Install"
        if: ${{ inputs.install != '' }}
        id: install
        run: ${{ inputs.install }}

      - name: "ESLint"
        id: eslint
        if: ${{ !cancelled() }}
        run: ${{ inputs.lint }}

      - name: "Prettier"
        if: ${{ !cancelled() && inputs.prettier != '' }}
        run: |
          npm run prettier:check

      - name: "Yamllint"
        if: ${{ !cancelled() && inputs.yamllint }}
        env:
          CONFIG: "{extends: relaxed, ignore: [node_modules/], rules: {line-length: {max: 119}}}"
        run: |
          echo "::group::List Files"
          yamllint -d '${{ env.CONFIG }}' --list-files .
          echo "::endgroup::"
          yamllint -d '${{ env.CONFIG }}' .

      - name: "Actionlint"
        if: ${{ !cancelled() && inputs.actionlint }}
        run: |
          echo "::group::Download"
          loc=$(curl -sI https://github.com/rhysd/actionlint/releases/latest | grep -i '^location:')
          echo "loc: ${loc}"
          tag=$(echo "${loc}" | sed -E 's|.*/tag/v?(.*)|\1|' | tr -d '\t\r\n')
          echo "tag: ${tag}"
          url="https://github.com/rhysd/actionlint/releases/latest/download/actionlint_${tag}_linux_amd64.tar.gz"
          echo "url: ${url}"
          curl -sL "${url}" | tar xz -C "${RUNNER_TEMP}" actionlint
          file "${RUNNER_TEMP}/actionlint"
          "${RUNNER_TEMP}/actionlint" --version
          echo "::endgroup::"
          "${RUNNER_TEMP}/actionlint" -color -verbose -shellcheck= -pyflakes=

      - name: "Verify action.yml"
        if: ${{ !cancelled() }}
        run: |
          yq -e '.runs.main | test("^dist/")' ${{ inputs.action }}
