name: "NPM Outdated"

on:
  workflow_call:

jobs:
  npm-outdated:
    name: "NPM Outdated"
    runs-on: ubuntu-latest
    timeout-minutes: 5

    permissions:
      pull-requests: write

    steps:
      - name: "Debug CTX github"
        continue-on-error: true
        env:
          GITHUB_CTX: ${{ toJSON(github) }}
        run: echo "$GITHUB_CTX"

      - name: "Debug Checkout ref"
        continue-on-error: true
        run: |
          echo "github.ref: ${{ github.ref }}"
          echo "github.event.pull_request.head.sha: ${{ github.event.pull_request.head.sha }}"
          echo "checkout ref: ${{ github.event.pull_request.head.sha || github.ref }}"

      - name: "Checkout"
        uses: actions/checkout@v5
        with:
          ref: ${{ github.event.pull_request.head.sha || github.ref }}

      - name: "Debug"
        continue-on-error: true
        run: |
          echo "::group::ls"
          ls -lAh .
          echo "::endgroup::"
          echo "::group::tree"
          tree .
          echo "::endgroup::"

      - name: "NPM Outdated Check"
        uses: cssnr/npm-outdated-action@latest
